version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    groups:
      gradle-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
